%% Script for plotting and correcting the graphs on the reports
figure('Units', 'inches',...
'Position', [0 0 10 3],...
'PaperPositionMode','auto');
plot((1:44)*0.39865,omega,'bo-');
axis([0 18 0 5]);

%'YTick',0:10e-3:500e-3,...
%%
%xlim([0 0.04]);
set(gca,...
'Units','normalized',...
'XTick',0:50:500,...
'YTick',0:0.1:1,...
'Position',[.15 .2 .75 .7],...
'FontUnits','points',...
'FontWeight','normal',...
'FontSize',9,...
'FontName','Times');
%%
xlabel('Time (s)',...
'FontUnits','points',...
'interpreter','latex',...  
'FontSize',11,...
'FontName','Times');
ylabel('Amplitude',...
'FontUnits','points',...
'FontWeight','normal',...
'FontSize',11,...
'FontName','Times');
legend({'Speech output'},...
'FontUnits','points',...
'interpreter','latex',...
'FontSize',11,...
'FontName','Times',...
'Location','NorthEast');
title('Speech using VCV Area Function',...
'FontUnits','points',...
'FontWeight','normal',...
'FontSize',14,...
'FontName','Times')
%% For surface plots we have
surf(fliplr(((0:72)/146)*1000),fliplr((1:44)*0.396825),V)
zlabel('Area (cm^2)',...
'FontUnits','points',...
'FontWeight','normal',...
'FontSize',11,...
'FontName','Times');
axis tight;
shading interp;
view([-40 30]);
%%
print -depsc2 SpeechOutputVCV.eps